from nmigen import Signal, Record


class InstructionStreamRecord(Record):
    def __init__(self):
        self.req_addr: Signal = ...
        self.req_valid: Signal = ...
        self.req_ready: Signal = ...

        self.rsp_data: Signal = ...
        self.rsp_valid: Signal = ...
        self.rsp_ready: Signal = ...


class DataStreamRecord(Record):
    def __init__(self):
        self.req_addr: Signal = ...
        self.req_data: Signal = ...
        self.req_we: Signal = ...
        self.req_size: Signal = ...
        self.req_unsigned: Signal = ...
        self.req_valid: Signal = ...
        self.req_ready: Signal = ...

        self.rsp_data: Signal = ...
        self.rsp_valid: Signal = ...
        self.rsp_ready: Signal = ...
